import React from "react";

const ServiceDiv = () => {
  const features = [
    {
      gif: "/gifs/create-video.gif",
      heading: "Create Ad Videos Instantly",
      description:
        "Turn text prompts and images into captivating video ads in minutes with our powerful AI video generator.",
    },
    {
      gif: "/gifs/image-creation.gif",
      heading: "Design Eye-Catching Ad Images",
      description:
        "Transform simple prompts into stunning ad creatives — perfect for Meta, Google, and more.",
    },
    {
      gif: "/gifs/ai-copy.gif",
      heading: "AI-Powered Ad Text & Descriptions",
      description:
        "Boost conversions with tailored ad copy and descriptions, all generated by our smart algorithm.",
    },
    {
      gif: "/gifs/pre-publish-score.gif",
      heading: "Pre-Publish Ad Score",
      description:
        "Analyze your ad's potential performance and fine-tune it before spending a single dollar.",
    },
    {
      gif: "/gifs/cross-publish.gif",
      heading: "Publish To Multiple Platforms",
      description:
        "Launch your campaigns directly to Meta, Google, and more — all from a unified platform.",
    },
    {
      gif: "/gifs/ai-insights.gif",
      heading: "AI Insights & Improvement Tips",
      description:
        "Analyze live campaigns, view performance reports, and get actionable recommendations for future ads.",
    },
  ];

  return (
    <div className="w-full mt-0 ">
      {/* Header Section */}
      <div className="w-full flex flex-col h-auto md:h-[40vh] font-kanit text-5xl justify-center items-center p-3 py-5 md:p-5">
        <h1 className="font-bold border-b px-3 border-black">
          <span
            className="bg-gradient-to-r from-orange-500 via-pink-500 to-purple-500 
               bg-clip-text text-transparent mr-2"
          >
            One
          </span>
          Platform
        </h1>
        <h1 className=" text-center text-2xl md:text-5xl py-4">
          All Your Marketing Needs.
        </h1>
        <h1
          className="text-3xl  bg-gradient-to-r from-orange-500 via-pink-500 to-purple-500 
               bg-clip-text text-transparent"
        >
          Unified in One Platform
        </h1>
        <p className="text-lg text-center pt-5 text-gray-600 w-full md:w-[60%]">
          Create high-impact ad assets, uncover actionable insights to maximize
          your campaigns, benchmark against competitors, and score your
          creatives — all from a single, unified platform.
        </p>
      </div>

      {/* Features Section */}
      <div className="w-full md:p-20 ">
        <div className="border-b border-r border-black p-0">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
            {features.map((item, index) => (
              <div
                key={index}
                className="border-t border-l border-black h-auto md:h-[80vh] p-5 flex flex-col"
              >
                {/* You can put a gif or icon here */}
                <div className="w-full h-40 md:h-[70%] mb-4">
                  {/* <img src={item.gif} alt="" className="w-full h-full object-contain" /> */}
                </div>

                {/* Heading and Description */}
                <div>
                  <h1 className="font-kanit p-2 text-3xl text-center">
                    {item.heading}
                  </h1>
                  <p className="font-kanit text-gray-600 text-center p-4">
                    {item.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ServiceDiv;
